export const localizedStrings = {
    products: {da: "Produkter", en:"Products", de: "Produkte"},
    events: {da: "Events", en:"Events", de: "Veranstaltungen"},
    ourAnimals: {da: "Vores dyr", en:"Our animals", de: "Unsere Tiere"},
    aboutMoseholm: {da: "Om Moseholm", en:"About Moseholm", de: "Über Moseholm"},
    practicalInfo: {da: "Praktisk info", en:"Pratical info", de: "Praktische Info"},
    theStore:{da: "Om gårdbutikken", en:"The farm shop", de: "der Hofladen"},
    theCafe:{da: "Praktisk info", en:"The café and prices", de: "Café und Preise"},
    titleFrontpage:{da: "Moseholm - økologisk gårdbutik", en:"Moseholm - organic farm shop", de: "Moseholm - ökologischer Hofladen"},
    heroHeader:{da: "Landoplevelse for hele familien", en:"Countryside experience for the entire family", de: "Landerlebnis für die ganze Familie"},
    heroText1:{da: "Moseholm er en 100% økologisk gårdbutik.", en:"Moseholm is a 100% organic farm shop.", de: "Moseholm ist ein 100 % biologischer Hofladen."},
    heroText2:{da: "Besøg vores café og hils på vores skønne dyr.", en:"Visit our café and meet our lovely animals.", de: "Besuchen Sie unser Café und begrüßen Sie unsere schönen Tiere."},
    ourProducts:{da: "Vores produkter", en:"Our products", de: "Unsere Produkte"},
    viewAllProducts:{da: "Se alle vores produkter", en:"View all products", de: "Alle Produkte sehen"},
    shopNow:{da: "Shop nu", en:"Shop now", de: "Jetzt einkaufen"},
    colonial:{da: "Kolonial", en:"Colonial", de: "Kolonial"},
    dairy:{da: "Mejeri", en:"Dairy", de: "Molkerei"},
    bread:{da: "Brød", en:"Bread", de: "Brot"},
    fruit:{da: "Frugt", en:"Fruit", de: "Frucht"},
    vegetables:{da: "Grøntsager", en:"Vegetables", de: "Gemüse"},
    meat:{da: "Kød", en:"Meat", de: "Fleisch"},
    visitBecause:{da: "Beøsg os fordi...", en:"Visit us because...", de: "Besuchen Sie uns, weil ..."},
    hundredOrganic:{da: "100% økologisk og lokalt fremstillede produkter", en:"100% organic and locally produced products", de: "100% biologische und lokal produzierte Produkte"},
    enjoyCafe:{da: "Nyd en hyggelig stund i vores hyggelige café", en:"Enjoy a cozy moment in our cozy café", de: "Genießen Sie einen gemütlichen Moment in unserem gemütlichen Café"},
    visitAnimals:{da: "Besøg vores søde og nysgerrige dyr", en:"Visit our cute and curious animals", de: "Besuchen Sie unsere süßen und neugierigen Tiere"},
    comingEvents:{da: "Kommende envets", en:"Upcoming events", de: "Kommende Veranstaltungen"},
    threeMore:{da: "Indlæs 3 mere", en:"View 3 more", de: "3 weitere laden"},
    viewAllEvents:{da: "Se alle events", en:"View all events", de: "Alle Veranstaltungen ansehen"},
    participateEvent:{da: "Deltag i et event og få en autentisk landoplevelse", en:"Attend an event and get an authentic country experience", de: "Besuchen Sie eine Veranstaltung und erleben Sie ein authentisches Landerlebnis"},
    helpAuntOda:{da: "Hjælp Moster Oda!", en:"Help Aunt Oda!", de: "Hilf Tante Oda!"},
    naughtyGoblin:{da: "Den frække skovnisse er igang med at skjule Moster Odas 3 æg.", en:"The naughty goblin is in the process of hiding Aunt Oda's 3 eggs.", de: "Der freche Specht versteckt gerade die 3 Eier von Tante Oda."},
    helpReturnEggs:{da: "Hjælp Moster Oda med at få æggene tilbage, så hun kan bage!", en:"Help Aunt Oda get the eggs back so she can bake!", de: "Hilf Tante Oda, die Eier zurückzubekommen, damit sie backen kann!"},
    imReady:{da: "Jeg er klar!", en:"I'm ready!", de: "ich bin bereit!"},
    contact:{da: "Kontakt", en:"Contact", de: "Kontakt"},
    openingHours:{da: "Åbningstider", en:"Opening hours", de: "Öffnungszeiten"},
    normalDays:{da: "Hverdage", en:"Weekdays", de: "Wochentags"},
    saturday:{da: "Lørdag", en:"Saturday", de: "Samstag"},
    sunday:{da: "Søndag", en:"Sunday", de: "Sonntag"},
    followUs:{da: "Følg os", en:"Follow us", de: "Folge uns"},
    
  }